name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        
    - name: fetch Ghidra
      run: |
        wget -O ${{ runner.temp }}/ghidra.zip https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_11.2_build/ghidra_11.2_PUBLIC_20240926.zip
        unzip -d ${{ runner.temp }} ${{ runner.temp }}/ghidra.zip
        
    - name: grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: build with Gradle
      run: ./gradlew buildExtension
      env:
        GHIDRA_INSTALL_DIR: ${{ runner.temp }}/ghidra_11.2_PUBLIC
        
    - name: exporting artefacts
      uses: actions/upload-artifact@v4
      with:
        name: fugue-ghidra-plugin
        path: |
          ${{ github.workspace }}/dist/*_fugue-ghidra.zip
